{"name": "Ошибка, при вводе несуществующего логина", "status": "passed", "start": 1717365899474, "stop": 1717365899677, "uuid": "cd32b876-606a-499d-a64e-59560101933a", "historyId": "b3ab2318d677111a65156cac00aff8f9", "testCaseId": "b3ab2318d677111a65156cac00aff8f9", "fullName": "tests.test_login_courier.TestLoginCourier#test_login_courier_with_wrong_login_error_404", "labels": [{"name": "story", "value": "Логин курьера"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "Rayless"}, {"name": "thread", "value": "23828-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}