{"name": "Ошибка, при вводе несуществующего логина", "status": "passed", "start": 1717365866176, "stop": 1717365866388, "uuid": "680c818f-f723-4109-8f5a-41790858de2d", "historyId": "b3ab2318d677111a65156cac00aff8f9", "testCaseId": "b3ab2318d677111a65156cac00aff8f9", "fullName": "tests.test_login_courier.TestLoginCourier#test_login_courier_with_wrong_login_error_404", "labels": [{"name": "story", "value": "Логин курьера"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "Rayless"}, {"name": "thread", "value": "117356-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}